ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."CALL_CENTER" CLUSTER BY (CC_CALL_CENTER_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."CATALOG_PAGE" CLUSTER BY (CP_CATALOG_PAGE_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."CATALOG_RETURNS" CLUSTER BY (CR_RETURNED_DATE_SK, CR_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."CATALOG_SALES" CLUSTER BY (CS_SOLD_DATE_SK, CS_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."CUSTOMER" CLUSTER BY (C_CUSTOMER_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."CUSTOMER_ADDRESS" CLUSTER BY (CA_ADDRESS_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."CUSTOMER_DEMOGRAPHICS" CLUSTER BY (CD_DEMO_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."DATE_DIM" CLUSTER BY (D_DATE_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."HOUSEHOLD_DEMOGRAPHICS" CLUSTER BY (HD_DEMO_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."INCOME_BAND" CLUSTER BY (IB_INCOME_BAND_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."INVENTORY" CLUSTER BY (INV_DATE_SK, INV_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."ITEM" CLUSTER BY (I_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."PROMOTION" CLUSTER BY (P_PROMO_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."REASON" CLUSTER BY (R_REASON_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."SHIP_MODE" CLUSTER BY (SM_SHIP_MODE_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."STORE" CLUSTER BY (S_STORE_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."STORE_RETURNS" CLUSTER BY (SR_RETURNED_DATE_SK, SR_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."STORE_SALES" CLUSTER BY (SS_SOLD_DATE_SK, SS_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."TIME_DIM" CLUSTER BY (T_TIME_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."WAREHOUSE" CLUSTER BY (W_WAREHOUSE_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."WEB_PAGE" CLUSTER BY (WP_WEB_PAGE_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."WEB_RETURNS" CLUSTER BY (WR_RETURNED_DATE_SK, WR_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."WEB_SALES" CLUSTER BY (WS_SOLD_DATE_SK, WS_ITEM_SK);

ALTER TABLE "BENCHMARK"."TPC_DS_SF10000"."WEB_SITE" CLUSTER BY (WEB_SITE_SK);
